spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate

cors:
  allowed-origins:
    - https://magampick.com
    - https://admin.magampick.com

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
