spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate

cors:
  allowed-origins:
    - https://dev.magampick.com
    - http://localhost:5173

auth:
  refresh-cookie:
    secure: true
